name: Run Selenium Script

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests to the main branch

jobs:
  run-selenium:
    runs-on: ubuntu-latest  # Specifies the type of runner to use

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installs dependencies from requirements.txt

      - name: Run Selenium script
        run: |
          python your_script.py  # Replace with the actual name of your script

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: freight-info-results
          path: updated_daily_indents_freight_info.csv  # Adjust if necessary
